#!/usr/bin/env python3
"""Generate the tiny synthetic reference + read fixtures for oxo-flow-circrna.

Layout (identical to the previous hand-made kit):
  reference/genome.fa        chr1 (1000 bp, hosts G1) + chr2 (200 bp decoy)
  reference/genes.gtf        G1 with three exons on chr1
  reference/hg38_ref.txt     CIRCexplorer2 ref: gene_id iso_id chrom strand
  raw/SAMPLE01_{1,2}.fastq.gz  ~200 read pairs; ~10% carry the exon3->exon2
                             back-splice junction so the circRNA callers
                             (CIRCexplorer2/find_circ/CIRIquant/
                             circrna_finder) have real fusion signal.

Regenerate with:  python3 test/fixtures/generate_fixtures.py
"""
import gzip
import os
import random

HERE = os.path.dirname(os.path.abspath(__file__))
REF = os.path.join(HERE, "reference")
RAW = os.path.join(HERE, "raw")
READ_LEN = 50
SEED = 42

# G1 exons on chr1 (1-based, inclusive); the BSJ joins e3 head -> e2 tail.
EXONS = [(100, 250), (400, 550), (700, 850)]


def build_reference():
    rng = random.Random(SEED)
    chr1 = "".join(rng.choice("ACGT") for _ in range(1000))
    chr2 = "".join(rng.choice("ACGT") for _ in range(200))
    os.makedirs(REF, exist_ok=True)
    with open(os.path.join(REF, "genome.fa"), "w") as f:
        f.write(">chr1\n")
        for i in range(0, len(chr1), 80):
            f.write(chr1[i : i + 80] + "\n")
        f.write(">chr2\n")
        for i in range(0, len(chr2), 80):
            f.write(chr2[i : i + 80] + "\n")
    with open(os.path.join(REF, "genes.gtf"), "w") as f:
        f.write('##generated by generate_fixtures.py (synthetic)\n')
        f.write('chr1\ttest\tgene\t100\t850\t.\t+\t.\tgene_id "G1";\n')
        for s, e in EXONS:
            f.write(
                f'chr1\ttest\texon\t{s}\t{e}\t.\t+\t.\tgene_id "G1"; '
                'transcript_id "G1_t1";\n'
            )
    with open(os.path.join(REF, "hg38_ref.txt"), "w") as f:
        # CIRCexplorer2's ref format: gene_id isoform_id chrom strand
        # (live: parse_ref got a 3-field 'chrom start end' line and
        # raised 'not enough values to unpack (expected 4, got 3)').
        f.write("G1\tG1_t1\tchr1\t+\n")
    return chr1, chr2


def bsj_pair(chr1):
    """Read pair with R1 spanning the exon3->exon2 back-splice junction."""
    e2, e3 = EXONS[1], EXONS[2]
    # 25 bp of e2's tail + 25 bp of e3's head = one 50 bp chimeric read
    r1 = chr1[e2[1] - 25 : e2[1]] + chr1[e3[0] - 1 : e3[0] - 1 + 25]
    # Mate sits downstream in e3
    pos = e3[0] + 30 - 1
    r2 = chr1[pos : pos + READ_LEN]
    return r1, r2


def regular_pair(chr1, rng):
    exon = rng.choice(EXONS)
    start = rng.randrange(exon[0] - 1, exon[1] - READ_LEN * 2)
    r1 = chr1[start : start + READ_LEN]
    r2 = chr1[start + READ_LEN + 40 : start + 2 * READ_LEN + 40]
    return r1, r2


def write_reads(chr1):
    os.makedirs(RAW, exist_ok=True)
    rng = random.Random(SEED + 7)
    pairs = []
    for _ in range(20):
        pairs.append(bsj_pair(chr1))
    for _ in range(180):
        pairs.append(regular_pair(chr1, rng))
    rng.shuffle(pairs)
    with gzip.open(os.path.join(RAW, "SAMPLE01_1.fastq.gz"), "wt") as f1, gzip.open(
        os.path.join(RAW, "SAMPLE01_2.fastq.gz"), "wt"
    ) as f2:
        for i, (r1, r2) in enumerate(pairs):
            name = f"@S1_{i}_BSJ" if i < 20 else f"@S1_{i}"
            f1.write(f"{name}\n{r1}\n+\n{'I' * READ_LEN}\n")
            f2.write(f"{name}\n{r2}\n+\n{'I' * READ_LEN}\n")


def main():
    chr1, _ = build_reference()
    write_reads(chr1)
    print("fixtures regenerated: 20 back-spliced + 180 regular pairs")


if __name__ == "__main__":
    main()
